# Largely references https://github.com/pydantic/pydantic-core/blob/0a5bbfc116c1659ce476fac56a44cda96673dfa8/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
      - next
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  workflow_dispatch:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all-targets

      - name: Run rustfmt
        run: cargo fmt --check

  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install pyproject dependencies
        run: uv sync --group dev

      - name: Install ruff
        run: uv tool install ruff

      - name: Run ruff
        run: uv run ruff check .

  test:
    name: Test on Python ${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Create virtualenv
        run: uv venv

      - name: Install tools
        run: uv tool install maturin && uv tool install pytest

      - name: Build and install package
        run: maturin develop

      - name: Run Rust tests
        run: cargo test

      - name: Run Python tests
        run: uv run pytest

  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          rust-toolchain: stable

      - name: Upload wheels
        uses: actions/upload-artifact@v5
        with:
          name: pypi_files_sdist
          path: dist

  build:
    name: Build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.interpreter || 'all' }}${{ matrix.os == 'linux' && format(' - {0}', matrix.manylinux == 'auto' && 'manylinux' || matrix.manylinux) || '' }})
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'

    strategy:
      fail-fast: false
      matrix:
        os: [linux, macos, windows]
        target: [undefined]
        manylinux: [auto]
        include:
          # manylinux
          - os: linux
            manylinux: auto
            target: aarch64
          - os: linux
            manylinux: auto
            target: armv7
            interpreter: "3.11 3.12 3.13 3.14"
          - os: linux
            manylinux: auto
            target: x86_64

          # musllinux
          - os: linux
            manylinux: musllinux_1_1
            target: x86_64
          - os: linux
            manylinux: musllinux_1_1
            target: aarch64
          - os: linux
            manylinux: musllinux_1_1
            target: armv7

          # macos
          - os: macos
            target: x86_64
          - os: macos
            target: aarch64

          # windows
          - os: windows
            target: x86_64
          - os: windows
            target: aarch64
            runs-on: windows-11-arm
            interpreter: "3.11 3.12 3.13 3.14"

        exclude:
          # was just a dummy variable to set a default value for target
          - target: undefined

    runs-on: ${{ matrix.runs-on || format('{0}-latest', (matrix.os == 'linux' && 'ubuntu') || matrix.os) }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          architecture: ${{ matrix.python-architecture || 'x64' }}

      - run: pip install -U twine 'ruff==0.5.0' typing_extensions

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          args: --release --out dist --interpreter ${{ matrix.interpreter || '3.11 3.12 3.13 3.14 pypy3.11' }}
          rust-toolchain: stable
          docker-options: -e CI

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} dist/

      - run: twine check --strict dist/*

      - name: Upload wheels
        uses: actions/upload-artifact@v5
        with:
          name: pypi_files_${{ matrix.os }}_${{ matrix.target }}_${{ matrix.interpreter || 'all' }}_${{ matrix.manylinux }}
          path: dist

  test-builds-arch:
    name: Test build on ${{ matrix.target }}-${{ matrix.distro }}
    needs: [build]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [armv7]
        distro: ["ubuntu22.04"]
        include:
          - target: aarch64
            distro: alpine_latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Get artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: pypi_files_linux_*
          merge-multiple: true
          path: dist

      - name: Install & test
        uses: uraimo/run-on-arch-action@v3.0.1
        with:
          arch: ${{ matrix.target }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          install: |
            set -x
            if command -v apt-get &> /dev/null; then
              echo "installing python & pip with apt-get..."
              apt-get update
              apt-get install -y --no-install-recommends python3.11 python3-pip python3.11-venv git curl
            else
              echo "installing python & pip with apk..."
              apk update
              apk add python3 py3-pip git curl
            fi
          env: |
            UV_NO_PROGRESS: '1'
          run: |
            set -x
            curl -LsSf https://astral.sh/uv/install.sh | sh
            source $HOME/.local/bin/env
            uv sync --no-install-project
            uv pip install rosu_pp_py --no-index --no-deps --find-links dist --force-reinstall
            uv run --no-sync python -c 'import rosu_pp_py;'

  test-builds-os:
    name: Test build on ${{ matrix.platform.os }}
    needs: [build]

    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            { os: linux, runs-on: ubuntu-latest },
            { os: linux_aarch64, runs-on: ubuntu-24.04-arm },
            { os: windows, runs-on: windows-latest },
            { os: windows_aarch64, runs-on: windows-11-arm },
            { os: macos, runs-on: macos-latest },
          ]

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Get artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: pypi_files_*
          merge-multiple: true
          path: dist

      - run: uv sync
      - run: uv pip install rosu_pp_py --no-index --no-deps --find-links dist --force-reinstall
      - run: uv run --no-sync python -c 'import rosu_pp_py;'

  release:
    name: Release
    needs: [clippy, ruff, test, test-builds-arch, test-builds-os, build-sdist]
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    environment:
      name: release

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Get artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: pypi_files_*
          merge-multiple: true
          path: dist

      - name: Test wheels integrity
        run: for whl in dist/*.whl; do unzip -qt "$whl"; done

      - name: Upload to PyPI
        run: uv publish --trusted-publishing always
